import { ping } from './ping';
import { help } from './help';
import { xp, xpAdmin, xpUser } from './xp';
import { disablexp } from './disablexp';
import { enablexp } from './enablexp';
import { addXpRole } from './addXpRole';
import { listXpRoles } from './listXpRoles';
import { editXpRole } from './editXpRole';
import { syncXpRoles } from './syncXpRoles';
import { music } from './music';
import { set } from './set';
import { addColorRole } from './addColorRole';
import { shop } from './shop';
import { buy } from './buy';
import { removeColorRole } from './removeColorRole';
import { ship } from './ship';
import { users } from './users';
import { ticket } from './ticket';
import { resetEconomy } from './resetEconomy';
import { dm } from './dm';
import { twitch } from './twitch';
import { youtube } from './youtube';

export const commands = [ping, help, xp, disablexp, enablexp, addXpRole, listXpRoles, editXpRole, syncXpRoles, addColorRole, removeColorRole, xpUser, xpAdmin, music, set, shop, buy, ship, users, ticket, resetEconomy, dm, twitch, youtube];